# -*- coding: utf-8 -*-
"""Demographic Data Analyzer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q67h6ubN7LZp2LtD0ObcXqMVxumZs8V4
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/adult.data.csv')
df.head()

#How many people of each race
df["race"].value_counts()

# Average age of men
average_age_men = df[df['sex'] == 'Male']['age'].mean()
print(average_age_men)

advanced_education = df['education'].isin(['Bachelors', 'Masters', 'Doctorate'])
percentage_advanced_education = (df[advanced_education]['salary'] == '>50K').mean() * 100
print(percentage_advanced_education)

percentage_bachelors = (df['education'] == 'Bachelors').mean()*100
print(percentage_bachelors)

percentage_non_advanced_education = (df[~advanced_education]['salary'] == '>50K').mean() * 100
print(percentage_non_advanced_education)

minimum_hours_per_week = df['hours-per-week'].min()
print(minimum_hours_per_week)

min_hours_high_salary = (df[df['hours-per-week'] == minimum_hours_per_week]['salary'] == '>50K').mean() * 100
print(min_hours_high_salary)

highest_earning_country_stats = df[df['salary'] == '>50K']['native-country'].value_counts()
print(highest_earning_country_stats)

highest_earning_country = highest_earning_country_stats.idxmax()
print(highest_earning_country)

indian_high_earners = df[df['native-country'] == 'India']['salary']=='>50K'

print("\n2. Average age of men:", average_age_men)
print("\n3. Percentage of people with a Bachelor's degree:", percentage_bachelors)
print("\n4. Percentage of people with advanced education making more than 50K:", percentage_advanced_education)
print("\n5. Percentage of people without advanced education making more than 50K:", percentage_non_advanced_education)
print("\n6. Minimum number of hours a person works per week:", minimum_hours_per_week)
print("\n7. Percentage of people who work the minimum hours and earn more than 50K:", min_hours_high_salary)
print("\n8. Country with the highest percentage of people earning >50K:", highest_earning_country)